### ISSUE TITLE
ScanPreferenceType not respected during upload

### ISSUE THREAD

**Issue by mtgibbs** [HPFOD/fod-uploader-java#1]
Swagger defines ScanPreferenceType as a string (either "Standard" or "Express"), but the call to start-scan from the uploader is ScanPreferenceId.  ScanPreferenceId becomes an ignored property and the scan defaults to Standard.

https://api.hpfod.com/swagger/ui/index#!/StaticScans/StaticScansV3_StartScan

**Comment by petebeegle** [comment]
Merged PR related to this
