### ISSUE TITLE
if more than 1 filter is being used when calling releases/assessment-types, a java exception is returned

### ISSUE THREAD

**Issue by tcappetto** [HPFOD/fod-uploader-java#11]
At one point, fod-uploader contacts FoD to find out which assessment types are valid for the ReleaseID.  If there are parameters on the commandline of fod-uploader that would result in that API call to have more than 1 filter, the call will fail and Java uploader will report a very generic Java exception.  In the API Logs however a very specific error is shown indicating  "Input String was not in a correct format" regarding the following API call

http://hpfod.com/api/v3/releases/123750/assessment-types?scanType=1&filters=frequencyTypeId:2+isBundledAssessment:true

It appears the url is not getting encoded when it is sent to FoD's API which is a requirement.

**Comment by mtgibbs** [comment]
https://github.com/HPFOD/fod-uploader-java/releases/tag/v3.0.1
