### ISSUE TITLE
-isBundledAssessment is not working 

### ISSUE THREAD

**Issue by cripher** [HPFOD/fod-uploader-java#12]
Description: 
- I am trying to start a scan and telling the command that I am using a bundled scan. 
- When I add -b, I am getting the java.lang.NullPointerException error. 
- I tried -b, --b, -B, -isBundledAssessment, -b 2, -b "True" 

![fodupload -b issue](https://user-images.githubusercontent.com/23040498/29822894-94d56b32-8cff-11e7-8e95-4f8250b72d40.png)

**Comment by mtgibbs** [comment]
What version of the uploader were you using?

**Comment by mtgibbs** [comment]
This is failing to properly get the Assessment Type back from the API and crashing because the data is null.  I doubt that this has anything to do with bundling.  Double check to make sure that you have valid assessment types in the FoD portal.

**Comment by mtgibbs** [comment]
Alright, @cripher.  I think I see the problem.
