### ISSUE TITLE
Connection timed out (write failed)

### ISSUE THREAD

**Issue by bill-hamilton** [HPFOD/fod-uploader-java#27]
Hello!

We are FOD customer. I tried using this tool (FYI it is only working on openjdk for me, not IBM jdk (1.8))

The upload process works fine, my EAR file is large (1.2 GB). But after the upload status - bytes sent... sends the whole file, things stop (at 1.2 GB which is correct) then nothing for a few mins. Finally I will get SotcketTimeoutException (com.fortify.fod.fodapi.controllers.StaticScanController.StartStaticScan(staticScanController.java:92))

I have used the command line option "-I 1" to no avail. Any help appreciated.

**Comment by mtgibbs** [comment]
Did you check the FoD portal and see if your payload had successfully been uploaded and your scan had been started?

**Comment by bill-hamilton** [comment]
Hey thanks for getting back. Nothing showing up on dashboard. At first, I had improperly formatted my file. That would show up on dash as "cancelled scan". I fixed up my zip to be like below, and the timeout started occurring now every time:

.
myApp.ear
workspace/
workspace/filexyz.java
workspace/subdir1
workspace/folder2/filezzz.java
workspace/file1.java

It seems like remote is extracting and / or inspecting my file after successful upload, causing the timeout on client side, or is my file incorrect?

**Comment by mtgibbs** [comment]
Sounds like the last chunk is failing to upload...  If the entire payload was uploaded, you would see a message saying something along the lines of:

`Scan # uploaded successfully.  Total bytes sent: ####`

The app only reports Bytes Sent on every 5th chunk.  Do you mind sharing with me the exact size in bytes your payload is?  Maybe you're the lucky one who found a funny offset bug.  😄

**Comment by bill-hamilton** [comment]
1769826172 bytes (sorry larger than I thought)

**Comment by mtgibbs** [comment]
I'm going to give this a few tests using the OpenJDK  and see if I can reproduce your problem.  Give me a few.

**Comment by bill-hamilton** [comment]
Which JDK is optimal? IBM's gives me some SSL errors. Is it because I have to add HTTPS cert to the keystore? I am not sure. It seems it might be a TLS related issue maybe?

**Comment by mtgibbs** [comment]
I had only tested it using Oracle's JDK (which should basically be the same).  Its been a minute since I've had to touch an IBM JVM, so I don't really know the problem there.  😉

**Comment by bill-hamilton** [comment]
Trying now with windows machine on oracle java 1.8.0_161. Will let you know how it goes (very slow upload speed on my windows machine)

**Comment by mtgibbs** [comment]
@bill-hamilton How did that upload go?

**Comment by bill-hamilton** [comment]
No luck. It failed with a timeout as well, but, it was not quite complete at the time of failure. I'd say about 90%. Also I can't upload using WEB UI either. It also times out (well it says HTTP error).

So my next attempt is to shrink the file. The .EAR has static content in it. 

Do you think I can unzip the ear, and all internal wars, delete static content, and submit the structure unzipped like so (contained in top level zip):

file.zip
_______________
/myapp.ear/file1.jar
/myapp.ear/app1.war/file2.jar
/workspace/file.java
/workspace/file2.java

Regards,

**Comment by mtgibbs** [comment]
Alright, well if there are problems getting this payload uploaded to the Web UI as well, it's probably time to escalate the problem to your TAM.  They'll be able to get that issue through to the right people to handle what's wrong and make sure that it is handled.

But!  Yes you can unzip the EAR file into multiple wars and delete all the images and whatnot.  Just make sure that you follow the accepted formats in the [documentation](https://ams.fortify.com/Docs/en/index.htm#Running_Asmnts/Static/StaticPrep/SP_Java.htm).

Typically when we're uploading our payloads, we strip everything but the source, classes, and jars from the build workspace before zipping since the scan isn't concerned with fonts, images, etc.
