### ISSUE TITLE
Authentication with portal credentials not working

### ISSUE THREAD

**Issue by reggiebIV** [HPFOD/fod-uploader-java#3]
When you attempt to authenticate with the user credentials (-uc), it fails to authorize

**Comment by mtgibbs** [comment]
Thanks, I'll take a look.  This in version 2.0.3?

**Comment by petebeegle** [comment]
Could you please provide the error you are receiving with any sensitive information omitted?

**Comment by reggiebIV** [comment]
It's 401 unauthorized. And I assume that it is 2.0.3 Matt, as I downloaded it yesterday.

**Comment by mtgibbs** [comment]
@reggiebIV 

Can you show us the command you issued (just falsify any user and tenant information)?  If you're getting a 401, it seems likely that you have gotten your account actually locked out or you have a special character in your password that is escaping the command line arguments out.

**Comment by reggiebIV** [comment]
Except you can immediately thereafter paste the same password in to the tenant portal and get authenticated immediately, and we I have reproduced this issue as reported by a client, so it's not just me. 

java -jar "fodupload.jar" -u "https://api.hpfod.com/bsi2.aspx?tid=1105&tc=ReggieApi&pv=106496&payloadType=ANALYSIS_PAYLOAD&astid=170&ts=.NET&ll=4.5" -z "c:\Users\Reggie\Downloads\mergefieldsdemo.zip" -uc reggie_brown_api [pass] -e 2706

java -jar "fodupload.jar" -u "https://api.hpfod.com/bsi2.aspx?tid=1105&tc=ReggieApi&pv=106496&payloadType=ANALYSIS_PAYLOAD&astid=170&ts=.NET&ll=4.5" -z "c:\Users\Reggie\Downloads\mergefieldsdemo.zip" -ac [key] [secret] -e 2706

I have tried including tenant id with username as well, all doesn't work. Detailed requests are all in a JIRA ticket.

**Comment by mtgibbs** [comment]
Please be sure to surround both the username and password in quotes individually or not use them at all.

```ps1
java -jar "fodupload.jar" -u "https://api.hpfod.com/bsi2.aspx?tid=1105&tc=ReggieApi&pv=106496&payloadType=ANALYSIS_PAYLOAD&astid=170&ts=.NET&ll=4.5" -z "c:\Users\Reggie\Downloads\mergefieldsdemo.zip" -uc "reggie_brown_api" "[pass]" -e 2706
```
