### ISSUE TITLE
Main.java always exits with Exit code 1

### ISSUE THREAD

**Issue by nahjil567** [HPFOD/fod-uploader-java#4]
This is an error code, and when this is included in a build step in jenkins it fails the build. Please return 0 when upload succeeds.

**Comment by mtgibbs** [comment]
I'm going to have to go back and see why it was 1 to begin with on exit.  Seems like oversight, but now we'll need to make sure everyone who's checking this status code in their own chains is aware of it.

**Comment by mtgibbs** [comment]
Yeah, that's clearly copy/paste code going on.  You want to PR it or wait til we get around to it?

**Comment by petebeegle** [comment]
Fixed in v2.0.4.
