### ISSUE TITLE
Add flag for isBundled

### ISSUE THREAD

**Issue by petebeegle** [HPFOD/fod-uploader-java#5]
I think it would just be a matter of allowing on the commandline a parameter for whether the assessment type is bundled such as -IsBundled 1, then when you call the API to Start Scans you supply that value for isBundledAssessment. 

Any logic that checks whether it really is bundled should be handled by the API. The default should be -IsBundled 0 in case the intent is to start a Static Premium without ever running a dynamic scan.

**Comment by Lateral-October** [comment]
I have a pull request that will be coming for this, once I also have a fix for issue #6 (as this won't work until that's corrected as well)
